### PR TITLE
SELinux cleanups

### PR DESCRIPTION
**Pull request by martinezjavier**
This pull requests renames the contrib directory to selinux, which is a more used convention in projects to store custom SELinux policy modules. I wonder though, if we shouldn't move to dist/selinux instead to keep all the dist files are there (probably adding subdirs for dbus, systemd, udev, etc).

It also adds a Makefile so users don't have to remember the commands to build and install the policy module.

### CODE REVIEW

**Comment by flihp** [comment]
Just merged #253 which is what probably caused the build error here. I just pushed the rebuild button on travis-ci which should hopefully fix the build failure on this PR.

**Comment by flihp** [comment]
@martinezjavier do you want this to go into the 1.x branch for the next release? I don't see any reason to leave it out given the delay in the tools and the fact that it's just a build change.

**Comment by martinezjavier** [comment]
Yes please, I meant it be for both branches but keep getting confused about which project prefers the PR against 1.x or master.

**Comment by flihp** [comment]
manually moved this over to 1.x and merged back into master.

**Pull request closed without merging**
